/**
 * TmuxSessionBackend — tmux as the PTY host for cloud-terminal sessions.
 *
 * Instead of spawning `claude`/`$SHELL` directly (child of the backend → dies
 * with it), the backend's node-pty spawns a tmux *client*. The tmux *server*
 * owns the real PTY and survives backend restarts; on boot the backend
 * reattaches to the surviving sessions.
 *
 * Process-tree constraints this class encodes:
 * - On the droplet the backend runs under systemd with KillMode=control-group.
 *   A tmux server forked by a client from inside the unit would inherit the
 *   unit's cgroup (daemonizing does NOT change the cgroup) and die on restart.
 *   There the server runs as its own unit and this class must NEVER start one
 *   implicitly — enforced via SPECWRIGHT_TMUX_SERVER=external and, as a
 *   belt-and-braces guard, via systemd detection (INVOCATION_ID), which also
 *   covers a droplet whose unit predates the new env vars.
 * - Locally (nodemon) the tmux server daemonizes out of the kill tree, so
 *   implicit start is fine.
 *
 * All subprocess calls use execFile with argv arrays — worktree paths and
 * session names can originate from client input, so no shell strings.
 */

import { execFile, execFileSync } from 'child_process';
import { promisify } from 'util';
import * as fs from 'fs';
import * as path from 'path';
import { checkCliAvailability } from '../model-config.js';
import {
  getLaunchDir,
  getTmuxConfigPath,
  getTmuxSocketPath,
} from '../utils/runtime-paths.js';
import type { CloudTerminalSessionId } from '../../shared/types/cloud-terminal.protocol.js';

const execFileAsync = promisify(execFile);

/** Minimum supported tmux version (prefix None, window-size latest, terminal-features). */
const MIN_TMUX_MAJOR = 3;
const MIN_TMUX_MINOR = 2;

/** Timeout for tmux management calls (list/kill/has/new/start). */
const TMUX_CALL_TIMEOUT_MS = 5_000;
/** capture-pane can be slower on long histories / slow disks. */
const TMUX_CAPTURE_TIMEOUT_MS = 10_000;

export type TmuxAvailability =
  | 'enabled'
  | 'disabled-by-flag'
  | 'not-installed'
  | 'version-too-old';

export interface RunScriptSpec {
  cwd: string;
  command: string;
  args: string[];
  env: Record<string, string>;
}

/**
 * Single-quote shell escaping: wraps in ', turning every embedded ' into '\''.
 * The output is safe to splice into a POSIX-sh script regardless of content
 * (newlines, $(...), backticks, unicode).
 */
export function sq(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/** Only env keys a POSIX shell accepts as identifiers make it into the run script. */
const ENV_KEY_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

/**
 * Renders the per-session launch script. Written to disk 0700 and passed to
 * `tmux new-session` as the (single, sq-quoted) shell command.
 *
 * Why a script instead of `new-session -e`/argv: the per-session env contains
 * secrets (GITHUB_TOKEN) and the initial prompt is arbitrary user text — argv
 * is ps-visible and any shell-string path is an injection surface. The script
 * also captures the inner command's real exit code (the tmux client's own exit
 * code says nothing about it).
 */
export function renderRunScript(spec: RunScriptSpec, exitCodePath: string): string {
  const lines: string[] = ['#!/bin/sh', '# generated by specwright cloud-terminal'];
  for (const [key, value] of Object.entries(spec.env)) {
    if (!ENV_KEY_RE.test(key)) continue;
    lines.push(`export ${key}=${sq(value)}`);
  }
  lines.push(`cd ${sq(spec.cwd)} || exit 97`);
  lines.push([spec.command, ...spec.args].map(sq).join(' '));
  lines.push('code=$?');
  lines.push(`printf '%s' "$code" > ${sq(exitCodePath)}`);
  lines.push('exit "$code"');
  return lines.join('\n') + '\n';
}

export class TmuxSessionBackend {
  private cachedAvailability?: TmuxAvailability;
  private terminalUpgradeAttempted = false;
  private configSynced = false;

  /** Overridable in tests. */
  protected socketPath(): string {
    return getTmuxSocketPath();
  }

  protected configPath(): string {
    return getTmuxConfigPath();
  }

  protected launchDir(): string {
    return getLaunchDir();
  }

  /**
   * True when this process must not start a tmux server implicitly: either the
   * droplet explicitly says so, or we detect we are running under systemd
   * (INVOCATION_ID) — a server forked here would land in the unit's cgroup and
   * die on the next restart, silently voiding the whole feature.
   */
  private serverIsExternal(): boolean {
    return process.env.SPECWRIGHT_TMUX_SERVER === 'external' || !!process.env.INVOCATION_ID;
  }

  /**
   * One-time probe, cached for the process lifetime.
   * SPECWRIGHT_TMUX=off is the kill switch back to direct spawn.
   */
  public availability(): TmuxAvailability {
    if (this.cachedAvailability) return this.cachedAvailability;
    this.cachedAvailability = this.probeAvailability();
    return this.cachedAvailability;
  }

  private probeAvailability(): TmuxAvailability {
    if (process.env.SPECWRIGHT_TMUX === 'off') return 'disabled-by-flag';
    if (!checkCliAvailability('tmux')) return 'not-installed';
    try {
      const out = execFileSync('tmux', ['-V'], { encoding: 'utf-8', timeout: TMUX_CALL_TIMEOUT_MS });
      const match = /(\d+)\.(\d+)/.exec(out);
      if (!match) return 'version-too-old';
      const [major, minor] = [parseInt(match[1], 10), parseInt(match[2], 10)];
      if (major > MIN_TMUX_MAJOR || (major === MIN_TMUX_MAJOR && minor >= MIN_TMUX_MINOR)) {
        return 'enabled';
      }
      return 'version-too-old';
    } catch {
      return 'not-installed';
    }
  }

  public isEnabled(): boolean {
    return this.availability() === 'enabled';
  }

  /** Human-readable startup log line (R2-M20: never fall back silently). */
  public logAvailability(): void {
    const state = this.availability();
    if (state === 'enabled') {
      console.log(
        `[TmuxSessionBackend] tmux backend enabled (socket: ${this.socketPath()}, server: ${this.serverIsExternal() ? 'external' : 'managed'})`
      );
    } else {
      const reason: Record<Exclude<TmuxAvailability, 'enabled'>, string> = {
        'disabled-by-flag': 'SPECWRIGHT_TMUX=off',
        'not-installed': 'tmux not found in PATH',
        'version-too-old': `tmux older than ${MIN_TMUX_MAJOR}.${MIN_TMUX_MINOR}`,
      };
      console.warn(
        `[TmuxSessionBackend] tmux backend DISABLED (${reason[state]}) — cloud-terminal sessions will NOT survive backend restarts`
      );
    }
  }

  private tmux(
    args: string[],
    timeoutMs: number = TMUX_CALL_TIMEOUT_MS
  ): Promise<{ ok: boolean; stdout: string; stderr: string }> {
    return execFileAsync('tmux', ['-S', this.socketPath(), ...args], {
      timeout: timeoutMs,
      encoding: 'utf-8',
      maxBuffer: 16 * 1024 * 1024,
    })
      .then(({ stdout, stderr }) => ({ ok: true, stdout, stderr }))
      .catch((err: Error & { stdout?: string; stderr?: string }) => ({
        ok: false,
        stdout: err.stdout ?? '',
        stderr: err.stderr ?? String(err.message ?? err),
      }));
  }

  /**
   * Functional server probe (a stale socket file must not count as "available").
   * Locally, starts the server on demand; in external/systemd mode it NEVER
   * starts one — dead socket means degraded direct-spawn mode.
   */
  public async ensureServerAvailable(): Promise<'ok' | 'unavailable'> {
    // list-sessions succeeds (with empty output) on a live server even with
    // zero sessions once `exit-empty off` is active — a functional probe.
    const probe = await this.tmux(['list-sessions']);
    if (probe.ok) {
      await this.syncConfig();
      await this.upgradeDefaultTerminal();
      return 'ok';
    }
    if (this.serverIsExternal()) {
      return 'unavailable';
    }
    const started = await this.tmux(['-f', this.configPath(), 'start-server']);
    if (!started.ok) {
      console.warn(`[TmuxSessionBackend] failed to start tmux server: ${started.stderr.trim()}`);
      return 'unavailable';
    }
    const reprobe = await this.tmux(['list-sessions']);
    if (reprobe.ok) {
      await this.syncConfig();
      await this.upgradeDefaultTerminal();
      return 'ok';
    }
    console.warn(`[TmuxSessionBackend] tmux server unreachable after start: ${reprobe.stderr.trim()}`);
    return 'unavailable';
  }

  /**
   * Re-applies tmux-cloud.conf to an ALREADY RUNNING server.
   *
   * `tmux -f <conf>` only reads the file when the client actually starts a new
   * server. Our server deliberately outlives backend restarts, so without this
   * a config change would never reach it — it would keep running whatever
   * config was in place when it first started (and only a kill-server, i.e.
   * losing every session, would fix that). Options are idempotent, so this runs
   * once per backend process before any session is created or reattached.
   *
   * Note: options land immediately, but per-client terminal capabilities
   * (terminal-overrides) are resolved at attach time — a client that is already
   * attached keeps the old set until it reattaches. The backend spawns fresh
   * attach clients on every restart, so that happens naturally.
   */
  private async syncConfig(): Promise<void> {
    if (this.configSynced) return;
    this.configSynced = true;
    const res = await this.tmux(['source-file', this.configPath()]);
    if (!res.ok) {
      console.warn(`[TmuxSessionBackend] source-file failed: ${res.stderr.trim()}`);
    }
  }

  /**
   * Upgrades default-terminal to tmux-256color when the host terminfo has the
   * entry (stock macOS ncurses often lacks it → the conf's screen-256color
   * fallback stands). Server-wide, applies to sessions created afterwards.
   */
  private async upgradeDefaultTerminal(): Promise<void> {
    if (this.terminalUpgradeAttempted) return;
    this.terminalUpgradeAttempted = true;
    try {
      await execFileAsync('infocmp', ['tmux-256color'], { timeout: TMUX_CALL_TIMEOUT_MS });
      await this.tmux(['set', '-g', 'default-terminal', 'tmux-256color']);
    } catch {
      // terminfo entry missing — keep screen-256color from the conf.
    }
  }

  /** tmux session name for a cloud-terminal session id. */
  public sessionName(sessionId: CloudTerminalSessionId): string {
    return `cs-${sessionId}`;
  }

  private exitCodePath(sessionId: CloudTerminalSessionId): string {
    return path.join(this.launchDir(), `exit-${sessionId}.code`);
  }

  private runScriptPath(sessionId: CloudTerminalSessionId): string {
    return path.join(this.launchDir(), `run-${sessionId}.sh`);
  }

  /**
   * Writes the per-session launch script (0700) and clears any stale exit-code
   * file. Returns the script path.
   */
  public async writeRunScript(
    sessionId: CloudTerminalSessionId,
    spec: RunScriptSpec
  ): Promise<string> {
    const dir = this.launchDir();
    await fs.promises.mkdir(dir, { recursive: true, mode: 0o700 });
    const scriptPath = this.runScriptPath(sessionId);
    const exitPath = this.exitCodePath(sessionId);
    await fs.promises.rm(exitPath, { force: true });
    await fs.promises.writeFile(scriptPath, renderRunScript(spec, exitPath), { mode: 0o700 });
    return scriptPath;
  }

  /** argv for creating a new detached-owner session running the launch script. */
  public buildNewSessionArgv(name: string, runScript: string): { shell: string; args: string[] } {
    return {
      shell: 'tmux',
      args: [
        '-S', this.socketPath(),
        '-f', this.configPath(),
        'new-session',
        '-s', name,
        // Single sq-quoted token: tmux hands the command string to sh -c, and
        // the script path may contain spaces.
        sq(runScript),
      ],
    };
  }

  /** argv for reattaching to a surviving session. `-d` kicks any stale client. */
  public buildAttachArgv(name: string): { shell: string; args: string[] } {
    return {
      shell: 'tmux',
      args: [
        '-S', this.socketPath(),
        '-f', this.configPath(),
        'attach-session', '-d', '-t', `=${name}`,
      ],
    };
  }

  /** Names of all live sessions on our socket. Dead server → empty set. */
  public async listSessions(): Promise<Set<string>> {
    const res = await this.tmux(['list-sessions', '-F', '#{session_name}']);
    if (!res.ok) return new Set();
    return new Set(res.stdout.split('\n').map((line) => line.trim()).filter(Boolean));
  }

  /** True when the named session is alive on our socket. */
  public async hasSession(name: string): Promise<boolean> {
    const res = await this.tmux(['has-session', '-t', `=${name}`]);
    return res.ok;
  }

  public async killSession(name: string): Promise<void> {
    const res = await this.tmux(['kill-session', '-t', `=${name}`]);
    if (!res.ok && !/can't find session|no server running/i.test(res.stderr)) {
      console.warn(`[TmuxSessionBackend] kill-session ${name} failed: ${res.stderr.trim()}`);
    }
  }

  /**
   * Scrollback HISTORY of the session's pane (visible screen excluded on
   * purpose: tmux fully redraws the screen to the client on attach, so
   * including it would duplicate content). `-e` keeps SGR escapes. Returns
   * null when there is no history or the call fails.
   */
  public async capturePaneHistory(name: string, maxLines: number): Promise<string | null> {
    const res = await this.tmux(
      ['capture-pane', '-p', '-e', '-t', `=${name}`, '-S', `-${maxLines}`, '-E', '-1'],
      TMUX_CAPTURE_TIMEOUT_MS
    );
    if (!res.ok || res.stdout.length === 0) return null;
    // capture-pane emits \n line endings; xterm.js needs \r\n.
    return res.stdout.replace(/\n/g, '\r\n');
  }

  /**
   * The pane as the user sees it: plain text (no SGR), soft-wrapped lines
   * joined (-J). `scrollbackLines` > 0 prepends that much history — for
   * content taller than the pane. Returns null when the call fails.
   */
  public async captureScreen(name: string, scrollbackLines = 0): Promise<string | null> {
    // `=name:` — capture-pane takes a PANE target; a bare `=name` is rejected
    // ("can't find pane", tmux 3.7c). The trailing colon selects the session's
    // current window and its active pane.
    const args = ['capture-pane', '-p', '-J', '-t', `=${name}:`];
    if (scrollbackLines > 0) args.push('-S', `-${scrollbackLines}`);
    const res = await this.tmux(args, TMUX_CAPTURE_TIMEOUT_MS);
    return res.ok && res.stdout.length > 0 ? res.stdout : null;
  }

  /** Inner command's exit code from the run script's exit file, if present. */
  public async readExitCode(sessionId: CloudTerminalSessionId): Promise<number | undefined> {
    try {
      const raw = await fs.promises.readFile(this.exitCodePath(sessionId), 'utf-8');
      const parsed = parseInt(raw.trim(), 10);
      return Number.isFinite(parsed) ? parsed : undefined;
    } catch {
      return undefined;
    }
  }

  /** Removes the run script + exit-code file of a finished/closed session. */
  public async cleanupSessionArtifacts(sessionId: CloudTerminalSessionId): Promise<void> {
    await fs.promises.rm(this.runScriptPath(sessionId), { force: true }).catch(() => {});
    await fs.promises.rm(this.exitCodePath(sessionId), { force: true }).catch(() => {});
  }

  /**
   * Kills `cs-*` sessions on our socket that no registry entry claims — their
   * metadata is unrecoverable, so they cannot be surfaced in the UI. Only ever
   * called with a healthy registry (an unreadable registry must NOT lead to
   * killing live sessions).
   */
  public async killOrphans(knownNames: Set<string>): Promise<void> {
    const live = await this.listSessions();
    for (const name of live) {
      if (name.startsWith('cs-') && !knownNames.has(name)) {
        console.warn(`[TmuxSessionBackend] killing orphaned tmux session ${name} (no registry entry)`);
        await this.killSession(name);
      }
    }
  }
}
